name: pywisher

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install isort
          pip install black
          
      - name: formatting imports and python code
        run: |
          black *.py
          isort *.py

      - name: commit changes
        run: |
          git config --local user.email "${ GITHUB_ACTOR }@users.noreply.github.com"
          git config --local user.name "${ GITHUB_ACTOR }"
          git add -A
          git commit -m "Automated Commit"
          git push
